### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by ghaffaru** [dbilovd/phussd#6]
Hi there !
Can you provide few resources for USSD PHP/Laravel development ?

Thanks

**Comment by dbilovd** [comment]
Hi @ghaffaru 

I am in the beginning stages of the resources for using this package. Kindly see the following:

* [How to install](https://github.com/dbilovd/php-ussd/blob/dev/docs/installation.md)
* [Building your first USSD application](https://github.com/dbilovd/php-ussd/blob/dev/docs/your-first-ussd-app.md)

I will be cleaning the documents and setting up a site shortly.

**Comment by ghaffaru** [comment]
Thats fine. 
Thanks
